;this file for FamiTone2 library generated by text2data tool

audio_data_music_data:
	db 2
	dw @instruments
	dw @samples-3
	dw @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,256,213
	dw @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,256,213

@instruments:
	db $30 ;instrument $00
	dw @env1,@env0,@env0
	db $00
	db $30 ;instrument $01
	dw @env2,@env0,@env0
	db $00

@samples:
@env0:
	db $c0,$00,$00
@env1:
	db $c7,$00,$00
@env2:
	db $c3,$00,$00


@song0ch0:
	db $fb,$06
@song0ch0loop:
@ref0:
	db $fb,$09,$80,$32,$00,$32,$83,$3c,$83,$40,$83,$44,$89,$3c,$3a,$36
	db $83,$47,$00,$47,$00,$46,$89,$45,$47,$4a,$89,$3c,$00,$3c,$00,$3c
	db $83,$3a,$83,$3c,$83,$40,$99,$32,$00,$32,$83,$3c,$83,$40,$83,$44
	db $89,$3c,$3a,$36,$83,$47,$00,$47,$00,$46,$89,$46,$00,$46,$00,$46
	db $00,$44,$85,$41,$3d,$3a,$83,$3c,$83,$40,$83,$3c,$97,$4a,$87,$46
	db $83,$44,$83,$40,$83,$44,$8b,$33,$00,$32,$83,$3c,$83,$00,$3c,$00
	db $3c,$00,$3c,$83,$3a,$83,$3c,$83,$40,$8f,$32,$00,$32,$83,$3c,$83
	db $40,$83,$44,$89,$3c,$3a,$36,$83,$47,$00,$47,$00,$46,$85,$46,$00
	db $46,$00,$44,$83,$41,$3c,$83,$3b,$3d,$41,$3c,$93
	db $fd
	dw @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref1:
	db $f9,$f9,$f9,$f9,$95
	db $fd
	dw @song0ch1loop

@song0ch2:
@song0ch2loop:
	db $ff,$05
	dw @ref1
	db $fd
	dw @song0ch2loop

@song0ch3:
@song0ch3loop:
	db $ff,$05
	dw @ref1
	db $fd
	dw @song0ch3loop

@song0ch4:
@song0ch4loop:
	db $ff,$05
	dw @ref1
	db $fd
	dw @song0ch4loop


@song1ch0:
	db $fb,$06
@song1ch0loop:
@ref5:
	db $fb,$10,$80,$3a,$44,$44,$48,$4c,$44,$4c,$48,$3a,$44,$44,$48,$4c
	db $45,$42,$3a,$44,$44,$48,$4c,$4e,$4c,$48,$44,$42,$3a,$3e,$42,$44
	db $45,$00,$3e,$42,$3e,$3a,$3e,$42,$45,$3a,$3e,$3a,$36,$35,$3a,$00
	db $3e,$42,$3e,$3a,$3e,$42,$44,$3e,$3a,$44,$42,$48,$44,$83,$00,$81
	db $fd
	dw @song1ch0loop

@song1ch1:
@song1ch1loop:
@ref6:
	db $82,$3a,$34,$34,$36,$3a,$34,$3a,$36,$36,$34,$34,$36,$3a,$35,$36
	db $36,$34,$34,$36,$3a,$3e,$3e,$3e,$3e,$3a,$3a,$36,$36,$34,$35,$00
	db $36,$3a,$36,$34,$36,$3a,$3f,$34,$36,$34,$30,$2d,$34,$00,$36,$3a
	db $36,$34,$36,$3a,$3e,$36,$34,$34,$36,$36,$34,$83,$00,$81
	db $fd
	dw @song1ch1loop

@song1ch2:
@song1ch2loop:
@ref7:
	db $f9,$89
	db $fd
	dw @song1ch2loop

@song1ch3:
@song1ch3loop:
@ref8:
	db $f9,$89
	db $fd
	dw @song1ch3loop

@song1ch4:
@song1ch4loop:
@ref9:
	db $f9,$89
	db $fd
	dw @song1ch4loop
